version: '3.8'

services:
  mcp-server:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./templates:/app/templates:ro
      - ./config:/app/config:ro
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mcp_platform
      POSTGRES_USER: mcp_user
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
